BPCS/Models/ContactModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BPCS.Models
{
    public class ContactModel
    {
        [Required]
        public String Name { get; set; }

        [Required]
        public String EmailAddress { get; set; }

        [Required]
        public String Message { get; set; }
    }
}

BPCS/Controllers/ContactController.cs
using BPCS.Models;
using SendGrid;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace BPCS.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(ContactModel model)
        {

            var message = new SendGridMessage();
            message.From = new MailAddress(model.EmailAddress);
            message.AddTo(ConfigurationManager.AppSettings["EmailTo"]);
            message.Text = model.Message;
            message.Subject = String.Format("Website email from {0} ", model.Name);

            var credentials = new NetworkCredential(ConfigurationManager.AppSettings["EmailUsername"], ConfigurationManager.AppSettings["EmailPassword"]);
            // Create an Web transport for sending email.
            var transportWeb = new Web(credentials);

            transportWeb.DeliverAsync(message);

            return View("ThankYou");
        }
    }
}

BPCS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BPCS.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

BPCS/Controllers/LinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BPCS.Controllers
{
    public class LinksController : Controller
    {
        // GET: Links
        public ActionResult Index()
        {
            return View();
        }
    }
}

BPCS/Controllers/MeetingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BPCS.Controllers
{
    public class MeetingsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

BPCS/Views/Contact/Index.cshtml
@model BPCS.Models.ContactModel
@{
    ViewBag.Title = "Contact Bexhill Prostate Cancer Support - Contact us";
}

<img src="~/Images/contact_us_1400x250.jpg" width="100%" alt="Contact Us"/>


<article>
    <h1>Contact</h1>
    <p>
        To send an enquiry or message please use the form below completing your name, email address and message.
    </p>
    @using (Html.BeginForm())
    {
        <div class="infoForm">
            <div class="inputLabel">
                @Html.LabelFor(x => x.Name)
                @Html.TextBoxFor(x => x.Name)
            </div>
            <div class="inputLabel">
                @Html.LabelFor(x => x.EmailAddress)
                @Html.TextBoxFor(x => x.EmailAddress)
            </div>
            <div class="inputTextbox">
                @Html.LabelFor(x => x.Message)
                @Html.TextAreaFor(x => x.Message, htmlAttributes: new { rows = 4, cols = 62 })
            </div>
            <div class="btn">
                <div class="btn-group">
                    <input type="submit" class="btn btn-default" />
                </div>
            </div>
        </div>

    }

</article>

BPCS/Views/Contact/ThankYou.cshtml
@model BPCS.Models.ContactModel
@{
    ViewBag.Title = "Contact Bexhill and Hastings Prostate Cancer Support - Thank you for your message";
}

<img src="~/Images/contact_us_1400x250.jpg" width="100%" alt="Contact Us" />

<article>
    <h1>Thank you</h1>

    <p>
        Your message has been sent, you should hear back from us soon.
    </p>
</article>

BPCS/Views/Home/Index.cshtml
@model BPCS.Models.ContactModel


@{
    ViewBag.Title = "Bexhill and Hastings Prostate Cancer Support";
}


<img src="~/Images/image-1500x400_higher.jpg" alt="Group at a meeting" width="100%"/>

<article id="main-home-article">
    <section id="main-home-section">
        <h1>Bexhill and Hastings Prostate Cancer Support</h1>
        <h2>Providing support and advice for those affected with prostate cancer in Bexhill and surrounding areas.</h2>
        <p>
            Bexhill and Hastings Prostate Cancer Support was setup in 2016 to provide support and advice for those living with
            prostate cancer in Bexhill, Hastings and surrounding areas.  Meetings are on the first Monday of the month,
            from 7-9pm at Bexhill Hospital, in the Health Centre building.  Meetings provide a chance for people to chat and share experiences as well as to hear from experts.
        </p>
        <br /><br />
        <p>
            For future meeting dates see @Html.ActionLink("meeting dates.", "Index", "Meetings")
        </p>
    </section>
</article>

BPCS/Views/Links/Index.cshtml
@{
    ViewBag.Title = "Contact and Hastings Bexhill Prostate Cancer Support - Links";
}

<img src="~/Images/www_1400x250.jpg" width="100%" alt="Web Image" />

<article>
    <div class="links">
        <h1>Links</h1>
        <div class="links">
            <ul>
                <li>
                    <a href="http://www.cowbeech.force9.co.uk/PCaSOEastbourne/forth.htm">
                    Eastbourne Prostate Cancer Support Group
        </a>
        </li>
        <li>
            <a href="http://pcaso.org/">
                Prostate Cancer Support Network
            </a>
        </li>
        <li>
            <a href="http://prostatecanceruk.org/">
                Prostate Cancer UK
            </a>
        </li>
        <li>
            <a href="http://www.nice.org.uk/guidance/cg175">
                NICE Clinical Guidance
            </a>
        </li>
        </ul>
    </div>
        </div>


</article>

BPCS/Views/Meetings/Index.cshtml
@model BPCS.Models.ContactModel


@{
    ViewBag.Title = "Bexhill and Hastings Prostate Cancer Support - Meetings";
}


<img src="~/Images/image-1500x400_higher.jpg" alt="Group at a meeting" width="100%"/>

<article id="main-home-article">
    <section id="main-home-section">
        <h1>Meeting Dates</h1>
        @*<br />
        <p>
            Meetings are held at the Health Center, Bexhill Hospital,
            Hollier Hill, TN40 2DZ
        </p>*@
        <br />
        <p>
            We will be having a social at a gastro pub on the 7th Jan 2019 at 7pm. 
            There is a tapas menu at £12 per head, drinks are not included.
            For more infomration and to reserve a place, please call John on 01424 532866.
            We will be meeting every other month though out the year. More information to follow.
        </p>
        <br /><br />

    </section>
</article>

BPCS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <header>
        <nav id="main-navigation">
            <ul>
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Meeting Dates", "Index", "Meetings")</li>
                <li>@Html.ActionLink("Contact", "Index", "Contact")</li>
                <li>@Html.ActionLink("Links", "Index", "Links")</li>
            </ul>
        </nav>
    </header>
    <section>
        @RenderBody()
    </section>
    <footer>

    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>